elastic-init:
    image: clakech/elastic-couchbase
    ports:
        - "9200:9200"
        - "9300:9300"
        - "9091:9091"
    environment:
        - INIT_CLUSTER=1
elastic:
    image: clakech/elastic-couchbase
    ports:
        - "9200"
        - "9300"
        - "9091"
couchbase-init:
    build: .
    ports:
        - "8091:8091"
couchbase:
    build: .
    links:
        - couchbase-init:couchbase
        - elastic-init:elastic-couchbase
    ports:
        - "8091"
couchbase-config:
    build: config
    links:
        - couchbase:couchbase
        - elastic-init:elastic-couchbase
    ports:
        - "8091"
    environment:
        - REBALANCE_CLUSTER

