elastic-init:
    image: clakech/elastic-couchbase
    ports:
        - "9200:9200"
        - "9300:9300"
        - "9091:9091"
    environment:
        - INIT_CLUSTER=1
elastic:
    image: clakech/elastic-couchbase
    ports:
        - "9200"
        - "9300"
        - "9091"
couchbase-init:
    build: .
    ports:
        - "8091:8091"
    links:
        - elastic:elastic-couchbase
couchbase:
    build: .
    links:
        - couchbase-init:couchbase

