elastic:
    container_name: elastic
    image: clakech/elastic-couchbase
    ports:
        - "9200:9200"
        - "9300:9300"
        - "9091:9091"
elastic2:
    container_name: elastic2
    image: clakech/elastic-couchbase
    ports:
        - "9201:9200"
        - "9301:9300"
        - "9092:9091"
couchbase:
    build: .
    command: sh wait_to_start.sh
    links:
        - elastic:elastic-couchbase
    environment:
        - WAIT_COMMAND=[ $(curl --write-out %{http_code} --silent --output /dev/null http://elastic-couchbase:9200/data) = 200 ]
        - WAIT_START_CMD=/init.sh
        - WAIT_SLEEP=2
        - WAIT_LOOPS=10
        - INIT_CLUSTER=1
    ports:
        - "8091:8091"
couchbase2:
    build: .
    command: sh wait_to_start.sh
    links:
        - couchbase
    environment:
        - WAIT_COMMAND=[ $(couchbase-cli server-list --cluster=localhost:8091 -u root -p foobar) = 342 ]
        - WAIT_START_CMD=/init.sh
        - WAIT_SLEEP=2
        - WAIT_LOOPS=10
    ports:
        - "8092:8091"
